# Defines our Vagrant environment
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  

  # create gold webgerver
  (1..3).each do |i|
  	config.vm.define "webg#{i}" do |webg|
  		config.ssh.insert_key = false
  		webg.vm.box = "ubuntu/trusty32"
  		webg.vm.hostname = "webg#{i}"
  		webg.vm.network :private_network, ip: "172.28.130.10#{i}"
  		webg.vm.network "forwarded_port", guest: 80, host: "810#{i}"
  		webg.vm.provider "virtualbox" do |vb|
  			vb.name = "webg#{i}"
  			vb.memory = "256"
  		end
  	end
  end	

  # create gold databaseservers
  (1..2).each do |i|
    config.vm.define "dbg#{i}" do |dbg|
      config.ssh.insert_key = false
      dbg.vm.box = "ubuntu/trusty32"
      dbg.vm.hostname = "dbg#{i}"
      dbg.vm.network :private_network, ip: "172.28.130.20#{i}"
      dbg.vm.provider "virtualbox" do |vb|
        vb.name = "dbg#{i}"
        vb.memory = "256"
      end
    end
  end 

  # create gold load balancer
  config.vm.define :lbg do |lbg_config|
      config.ssh.insert_key = false
      lbg_config.vm.box = "ubuntu/trusty32"
      lbg_config.vm.hostname = "lbg"
      lbg_config.vm.network :private_network, ip: "172.28.130.99"
      lbg_config.vm.network "forwarded_port", guest: 80, host: 8199
      lbg_config.vm.provider "virtualbox" do |vb|
        vb.name = "lbg"
        vb.memory = "256"
      end
  end
end

