# Defines our Vagrant environment
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # create silver webserver
  (1..2).each do |i|
  	config.vm.define "webs#{i}" do |webs|
  		config.ssh.insert_key = false
  		webs.vm.box = "ubuntu/trusty64"
  		webs.vm.hostname = "webs#{i}"
  		webs.vm.network :private_network, ip: "172.28.129.10#{i}"
  		webs.vm.network "forwarded_port", guest: 80, host: "809#{i}"
  		webs.vm.provider "virtualbox" do |vb|
  			vb.name = "webs#{i}"
  			vb.memory = "256"
  		end
  	end
  end	
  config.vm.provision "ansible" do |ansible|
  	ansible.playbook = "ansible/installweb.yml"
  	ansible.inventory_path = "ansible/hosts"
  end

  # create silver database server
  config.vm.define :dbs do |dbs|
  	dbs.vm.box = "ubuntu/trusty64"
  	config.ssh.insert_key = false
  	dbs.vm.hostname = "dbs"
  	dbs.vm.network :private_network, ip: "172.28.129.201"
  	dbs.vm.provider "virtualbox" do |vb|
  		vb.name = "dbs"
  		vb.memory = "256"
  	end
  end
  config.vm.provision "ansible" do |ansible|
  	ansible.playbook = "ansible/installdb.yml"
  	ansible.inventory_path = "ansible/hosts"
  end
end
